exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Layers
subtitle: "Layers Music Project"
url: "http://www.layermusicproject.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
# descriptions:
  # - cat: jekyll
  #   desc: "Posts describing Jekyll setup techniques."

  # - cat: dummy
  #   desc: "Just some placeholder posts, lorem ipsum and the rest."


twitter_username:     LayerProject
youtube_username:     layeryb
soundcloud_username:  layer-music-project
facebook_username:    layermusicproject

plugins_dir:
  - jekyll-soundcloud
